# Generated by Django 5.0 on 2023-12-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson_course_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
