# Generated by Django 4.2.8 on 2023-12-26 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_pay_paid_course_alter_pay_paid_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата выхода урока'),
            preserve_default=False,
        ),
    ]
